repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    implementation project(':core')
    implementation project(':items')
    implementation project(':storage')
    testImplementation("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
    testImplementation("com.github.MockBukkit:MockBukkit:v4.110.0") {
        exclude group: "org.junit.jupiter"
        exclude group: "org.junit.platform"
        exclude group: "org.junit"
    }
}
